.github/workflows/publish-pypi.yml

Adds:
* action that publishes the package on pypi
* triggered by new releases
Closes #7

📦 Add pypi publishing

---

.github/workflows/publish-pypi.yml

🐛 Fix version check in PyPI publishing

---

.github/workflows/publish-pypi.yml

🐛 Fix workflow by adding environment

---

docs/conf.py
tests/clean.bat
tests/test_problem_definition.py

📄 fix(doc/tests) rename project name in doc and add windows clean script

---

docs/source/notebooks/sample.ipynb
examples/containers/sample_example.py
src/plaid/containers/sample.py
src/plaid/utils/cgns_helper.py
tests/conftest.py
tests/containers/test_dataset.py
tests/containers/test_sample.py
tests/utils/test_cgns_helper.py
tests/utils/test_interpolation.py
tests/utils/test_split.py

Move function and get the version from https://gitlab.com/drti/muscat/-/blob/master/src/Muscat/Bridges/CGNSBridge.py?ref_type=heads#L711 
Minor cleanup as well

♻️ feat(show_cgns_tree) improve and move to utils/cgns_helper.py

---

.pre-commit-config.yaml
README.md
conda_dev_env.yml
docs/source/getting_started.md
pyproject.toml

🎉  Add pre-commit for developers

---

src/plaid/containers/sample.py

🐛 fix(samples) add time_series summary in __str__

---

src/plaid/constants.py
src/plaid/containers/sample.py

📄 add constant CGNS_FIELD_LOCATIONS and improve doctrings accordingly

---

.github/pull_request_template.md
CHANGELOG.md

📄 (CHANGELOG.md) Initiate; (pull_request_template.md) add checklist

---

.readthedocs.yml

🐛 fix(.readthedocs.yml) remove git:depth option

---

.readthedocs.yml
CHANGELOG.md
docs/conf.py
docs/source/notebooks/metrics.ipynb
src/plaid/bridges/huggingface_bridge.py

🐛 fix(docs) correct doc compilation

---

.github/workflows/doc.yml
.github/workflows/lint-format-check.yaml
.github/workflows/pr-title-checker.yml
.github/workflows/publish-pypi.yml
.github/workflows/testing.yml
.readthedocs.yml
CHANGELOG.md
src/plaid/pipelines/plaid_blocks.py
src/plaid/pipelines/sklearn_block_wrappers.py
src/plaid/types/feature_types.py

📦 feat(.github) Update actions versions

---

src/plaid/containers/dataset.py
src/plaid/containers/sample.py
src/plaid/containers/utils.py
src/plaid/types/__init__.py
src/plaid/types/feature_types.py

♻️ rename types to remove Type from name of types

---

CHANGELOG.md
src/plaid/containers/dataset.py
src/plaid/containers/sample.py
src/plaid/containers/utils.py
src/plaid/types/__init__.py
src/plaid/types/feature_types.py

fix CHANGELOG

---

CHANGELOG.md
src/plaid/pipelines/plaid_blocks.py
tests/pipelines/test_plaid_blocks.py

🎉 feat(pipelines/plaid_blocks.py) add column transformer inverse_transform

---

src/plaid/utils/interpolation.py

📄(utils.interpolation) fix docstrings style

---

CHANGELOG.md
src/plaid/containers/sample.py
tests/containers/test_sample.py

🎉 Add methods to `Sample` and `Dataset` to summarize and check their content
Thanks for contributing! Please make sure your PR title and content follow the guidelines.
Leave this checklist below in your PR description and tick the corresponding boxes.
Your PR title **must start with one of the following emojis** to indicate the type of change:
- 🐛 Bug fix
- 📄 Documentation
- 🎉 New feature or initial commit
- 🚀 Performance or deployment
- ♻️ Refactor or cleanup
- 📦 Packaging or dependency management (e.g., pyproject.toml, conda, Poetry, pre-commit)
**Example:**
🎉 Add MMD-based split method
---
This PR implements new summarization methods for `Sample` and `Dataset` classes to provide better content inspection capabilities:
**For `Sample` class:**
- Added methods that provide more detailed …

🎉 Update sample.py

---

src/plaid/containers/dataset.py

:recycle: refactor: use FeatureIdentifier type in dataset.py

---

CHANGELOG.md
src/plaid/containers/dataset.py
tests/containers/test_dataset.py

🐛(dataset) fix tabular from multidimensional scalars

---

CHANGELOG.md
docs/Makefile
examples/examples/downloadable_example.py
examples/problem_definition_example.py

📄 fix(doc notebooks) remove depracted functions uses and dl for examples (robustifies doc wrt to API changes)

---

docs/conf.py
docs/source/quickstart.md
src/plaid/bridges/huggingface_bridge.py

📄 feat(docs) minor improvements

---

.github/workflows/publish-pypi.yml

🐛Fix pypi action

---

.github/workflows/testing.yml

🚀update testing.yml rules to run only when necessary

---

CHANGELOG.md
src/plaid/containers/sample.py
tests/containers/test_sample.py

🎉Add Sample.del_feature
